### ISSUE TITLE
Todo：『#あぱと飯テロ対決』 めるVSあぱの勝利数をEmbedに出力

### ISSUE THREAD

**Issue by Meru7** [SpaceServerNet/Cosumo-Chan#17]
![Screenshot_20201231-211308](https://user-images.githubusercontent.com/64207094/103410139-602e3b00-4bad-11eb-9c36-ffd19fabd46d.png)

今までの対決を数えてEmbedに出力。

**Comment by Merutan** [comment]
> 2021年の戦歴  

**あぱ 1 vs 0 める**

**Comment by Merutan** [comment]
あぱがズルするから本当にBANしたい
