### ISSUE TITLE
Todo：V3.0の作成

### ISSUE THREAD

**Issue by Meru7** [SpaceServerNet/Cosumo-Chan#4]
2021年に正式稼働する予定のコスモちゃんBotのTodoをissueを通じて書いておく。

**Comment by Natu9** [comment]
**アップデートパッチノート仮置き**
----

コスモちゃんBotの新バージョン **『CosumoSystem』v3.0.0**が配信されました。変更点は以下の通りです。

- BuildName `4.2021.1`
- PatchCode `Ver3.0`

----
# v3.0.0

**Comment by Natu9** [comment]
ReadMeの変更
https://github.com/CosumoChan/Cosumo-Chan/commit/913fafb56d0b085129f57f1c7b8cf09bdddc5d3b
